/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "my-design.v:1.1-42.10" *)
module half_adder_scan(clk, rst_n, a_in, b_in, scan_en, scan_in, scan_out, sum, carry);
  (* src = "my-design.v:23.3-34.6" *)
  wire _00_;
  (* src = "my-design.v:23.3-34.6" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "my-design.v:20.7-20.11" *)
  wire a_ff;
  (* src = "my-design.v:6.12-6.16" *)
  input a_in;
  wire a_in;
  (* src = "my-design.v:20.13-20.17" *)
  wire b_ff;
  (* src = "my-design.v:7.12-7.16" *)
  input b_in;
  wire b_in;
  (* src = "my-design.v:16.12-16.17" *)
  output carry;
  wire carry;
  (* src = "my-design.v:2.12-2.15" *)
  input clk;
  wire clk;
  (* src = "my-design.v:3.12-3.17" *)
  input rst_n;
  wire rst_n;
  (* src = "my-design.v:10.12-10.19" *)
  input scan_en;
  wire scan_en;
  (* src = "my-design.v:11.12-11.19" *)
  input scan_in;
  wire scan_in;
  (* src = "my-design.v:12.12-12.20" *)
  output scan_out;
  wire scan_out;
  (* src = "my-design.v:15.12-15.15" *)
  output sum;
  wire sum;
  NOT _12_ (
    .A(b_ff),
    .Y(_04_)
  );
  NOT _13_ (
    .A(a_ff),
    .Y(_05_)
  );
  NOT _14_ (
    .A(scan_en),
    .Y(_06_)
  );
  NOT _15_ (
    .A(rst_n),
    .Y(_02_)
  );
  NOR _16_ (
    .A(_04_),
    .B(_05_),
    .Y(carry)
  );
  NAND _17_ (
    .A(b_in),
    .B(_06_),
    .Y(_07_)
  );
  NAND _18_ (
    .A(a_ff),
    .B(scan_en),
    .Y(_08_)
  );
  NAND _19_ (
    .A(_07_),
    .B(_08_),
    .Y(_01_)
  );
  NAND _20_ (
    .A(_06_),
    .B(a_in),
    .Y(_09_)
  );
  NAND _21_ (
    .A(scan_en),
    .B(scan_in),
    .Y(_10_)
  );
  NAND _22_ (
    .A(_09_),
    .B(_10_),
    .Y(_00_)
  );
  NOR _23_ (
    .A(b_ff),
    .B(a_ff),
    .Y(_11_)
  );
  NOR _24_ (
    .A(carry),
    .B(_11_),
    .Y(sum)
  );
  NOT _25_ (
    .A(rst_n),
    .Y(_03_)
  );
  (* src = "my-design.v:23.3-34.6" *)
  DFFSR _26_ (
    .C(clk),
    .D(_00_),
    .Q(a_ff),
    .R(_02_),
    .S(1'h0)
  );
  (* src = "my-design.v:23.3-34.6" *)
  DFFSR _27_ (
    .C(clk),
    .D(_01_),
    .Q(b_ff),
    .R(_03_),
    .S(1'h0)
  );
  assign scan_out = b_ff;
endmodule
