/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-03 23:56:28
*/

module hamming_codec
(
  clk,
  rst,
  data_in,
  data_out,
  sin,
  shift,
  sout,
  tck,
  test,
  _133_,
  \_133_.d ,
  _134_,
  \_134_.d ,
  _135_,
  \_135_.d ,
  _136_,
  \_136_.d ,
  _137_,
  \_137_.d ,
  _138_,
  \_138_.d ,
  _139_,
  \_139_.d ,
  _140_,
  \_140_.d ,
  \__uuf__._82_ ,
  \\__uuf__._82_.d ,
  \__uuf__._83_ ,
  \\__uuf__._83_.d ,
  \__uuf__._84_ ,
  \\__uuf__._84_.d ,
  \__uuf__._85_ ,
  \\__uuf__._85_.d ,
  \__uuf__._86_ ,
  \\__uuf__._86_.d ,
  \__uuf__._87_ ,
  \\__uuf__._87_.d ,
  \__uuf__._88_ ,
  \\__uuf__._88_.d ,
  \__uuf__._89_ ,
  \\__uuf__._89_.d ,
  \__uuf__._90_ ,
  \\__uuf__._90_.d ,
  \__uuf__._91_ ,
  \\__uuf__._91_.d ,
  \__uuf__._92_ ,
  \\__uuf__._92_.d 
);

  input _133_;
  output \_133_.d ;
  input _134_;
  output \_134_.d ;
  input _135_;
  output \_135_.d ;
  input _136_;
  output \_136_.d ;
  input _137_;
  output \_137_.d ;
  input _138_;
  output \_138_.d ;
  input _139_;
  output \_139_.d ;
  input _140_;
  output \_140_.d ;
  input \__uuf__._82_ ;
  output \\__uuf__._82_.d ;
  input \__uuf__._83_ ;
  output \\__uuf__._83_.d ;
  input \__uuf__._84_ ;
  output \\__uuf__._84_.d ;
  input \__uuf__._85_ ;
  output \\__uuf__._85_.d ;
  input \__uuf__._86_ ;
  output \\__uuf__._86_.d ;
  input \__uuf__._87_ ;
  output \\__uuf__._87_.d ;
  input \__uuf__._88_ ;
  output \\__uuf__._88_.d ;
  input \__uuf__._89_ ;
  output \\__uuf__._89_.d ;
  input \__uuf__._90_ ;
  output \\__uuf__._90_.d ;
  input \__uuf__._91_ ;
  output \\__uuf__._91_.d ;
  input \__uuf__._92_ ;
  output \\__uuf__._92_.d ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire \__BoundaryScanRegister_input__0__.dout ;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_input__1__.dout ;
  wire \__BoundaryScanRegister_input__1__.sout ;
  wire \__BoundaryScanRegister_input__2__.dout ;
  wire \__BoundaryScanRegister_input__2__.sout ;
  wire \__BoundaryScanRegister_input__3__.dout ;
  wire \__BoundaryScanRegister_input__3__.sout ;
  wire \__BoundaryScanRegister_output__4__.din ;
  wire \__BoundaryScanRegister_output__4__.sin ;
  wire \__BoundaryScanRegister_output__4__.sout ;
  wire \__BoundaryScanRegister_output__5__.din ;
  wire \__BoundaryScanRegister_output__5__.sout ;
  wire \__BoundaryScanRegister_output__6__.din ;
  wire \__BoundaryScanRegister_output__6__.sout ;
  wire \__uuf__._00_ ;
  wire \__uuf__._01_ ;
  wire \__uuf__._02_ ;
  wire \__uuf__._03_ ;
  wire \__uuf__._04_ ;
  wire \__uuf__._05_ ;
  wire \__uuf__._06_ ;
  wire \__uuf__._07_ ;
  wire \__uuf__._08_ ;
  wire \__uuf__._09_ ;
  wire \__uuf__._10_ ;
  wire \__uuf__._11_ ;
  wire \__uuf__._12_ ;
  wire \__uuf__._13_ ;
  wire \__uuf__._14_ ;
  wire \__uuf__._15_ ;
  wire \__uuf__._16_ ;
  wire \__uuf__._17_ ;
  wire \__uuf__._18_ ;
  wire \__uuf__._19_ ;
  wire \__uuf__._20_ ;
  wire \__uuf__._21_ ;
  wire \__uuf__._22_ ;
  wire \__uuf__._23_ ;
  wire \__uuf__._24_ ;
  wire \__uuf__._25_ ;
  wire \__uuf__._26_ ;
  wire \__uuf__._27_ ;
  wire \__uuf__._28_ ;
  wire \__uuf__._29_ ;
  wire \__uuf__._30_ ;
  wire \__uuf__._31_ ;
  wire \__uuf__._32_ ;
  wire \__uuf__._33_ ;
  wire \__uuf__._34_ ;
  wire \__uuf__._35_ ;
  wire \__uuf__._36_ ;
  wire \__uuf__._37_ ;
  wire \__uuf__._38_ ;
  wire \__uuf__._39_ ;
  wire \__uuf__._40_ ;
  wire \__uuf__.__clk_source__ ;
  wire \__uuf__.code_reg[0] ;
  wire \__uuf__.code_reg[1] ;
  wire \__uuf__.code_reg[2] ;
  wire \__uuf__.code_reg[3] ;
  wire \__uuf__.code_reg[4] ;
  wire \__uuf__.code_reg[5] ;
  wire \__uuf__.code_reg[6] ;
  input clk;
  wire clk;
  input [3:0] data_in;
  wire [3:0] data_in;
  output [3:0] data_out;
  wire [3:0] data_out;
  input rst;
  wire rst;
  input shift;
  wire shift;
  input sin;
  wire sin;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;

  INVX1
  _064_
  (
    .A(rst),
    .Y(_000_)
  );


  INVX1
  _065_
  (
    .A(\__BoundaryScanRegister_output__4__.din ),
    .Y(_044_)
  );


  INVX1
  _066_
  (
    .A(\__BoundaryScanRegister_output__4__.sin ),
    .Y(_045_)
  );


  INVX1
  _067_
  (
    .A(\__BoundaryScanRegister_output__5__.din ),
    .Y(_046_)
  );


  INVX1
  _068_
  (
    .A(\__BoundaryScanRegister_output__6__.din ),
    .Y(_047_)
  );


  INVX1
  _069_
  (
    .A(clk),
    .Y(_048_)
  );


  INVX1
  _070_
  (
    .A(\__uuf__._07_ ),
    .Y(_049_)
  );


  INVX1
  _071_
  (
    .A(\__uuf__._06_ ),
    .Y(_050_)
  );


  INVX1
  _072_
  (
    .A(\__uuf__._05_ ),
    .Y(_051_)
  );


  INVX1
  _073_
  (
    .A(\__uuf__._04_ ),
    .Y(_052_)
  );


  INVX1
  _074_
  (
    .A(\__uuf__._03_ ),
    .Y(_053_)
  );


  INVX1
  _075_
  (
    .A(\__uuf__._02_ ),
    .Y(_054_)
  );


  INVX1
  _076_
  (
    .A(\__uuf__._01_ ),
    .Y(_055_)
  );


  INVX1
  _077_
  (
    .A(\__uuf__._00_ ),
    .Y(_056_)
  );


  MUX2X1
  _078_
  (
    .A(\__BoundaryScanRegister_input__0__.sout ),
    .B(data_in[0]),
    .S(test),
    .Y(_057_)
  );


  INVX1
  _079_
  (
    .A(_057_),
    .Y(\__BoundaryScanRegister_input__0__.dout )
  );


  NAND2X1
  _080_
  (
    .A(sin),
    .B(shift),
    .Y(_058_)
  );


  OAI21X1
  _081_
  (
    .A(shift),
    .B(_057_),
    .C(_058_),
    .Y(_008_)
  );


  MUX2X1
  _082_
  (
    .A(\__BoundaryScanRegister_input__1__.sout ),
    .B(data_in[1]),
    .S(test),
    .Y(_059_)
  );


  INVX1
  _083_
  (
    .A(_059_),
    .Y(\__BoundaryScanRegister_input__1__.dout )
  );


  NAND2X1
  _084_
  (
    .A(\__BoundaryScanRegister_input__0__.sout ),
    .B(shift),
    .Y(_060_)
  );


  OAI21X1
  _085_
  (
    .A(shift),
    .B(_059_),
    .C(_060_),
    .Y(_009_)
  );


  MUX2X1
  _086_
  (
    .A(\__BoundaryScanRegister_input__2__.sout ),
    .B(data_in[2]),
    .S(test),
    .Y(_061_)
  );


  INVX1
  _087_
  (
    .A(_061_),
    .Y(\__BoundaryScanRegister_input__2__.dout )
  );


  NAND2X1
  _088_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_input__1__.sout ),
    .Y(_062_)
  );


  OAI21X1
  _089_
  (
    .A(shift),
    .B(_061_),
    .C(_062_),
    .Y(_010_)
  );


  MUX2X1
  _090_
  (
    .A(\__BoundaryScanRegister_input__3__.sout ),
    .B(data_in[3]),
    .S(test),
    .Y(_063_)
  );


  INVX1
  _091_
  (
    .A(_063_),
    .Y(\__BoundaryScanRegister_input__3__.dout )
  );


  NAND2X1
  _092_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_input__2__.sout ),
    .Y(_027_)
  );


  OAI21X1
  _093_
  (
    .A(shift),
    .B(_063_),
    .C(_027_),
    .Y(_011_)
  );


  NAND2X1
  _094_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_output__4__.sin ),
    .Y(_028_)
  );


  OAI21X1
  _095_
  (
    .A(shift),
    .B(_044_),
    .C(_028_),
    .Y(_012_)
  );


  NAND2X1
  _096_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_output__4__.sout ),
    .Y(_029_)
  );


  OAI21X1
  _097_
  (
    .A(shift),
    .B(_046_),
    .C(_029_),
    .Y(_013_)
  );


  NAND2X1
  _098_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_output__5__.sout ),
    .Y(_030_)
  );


  OAI21X1
  _099_
  (
    .A(shift),
    .B(_047_),
    .C(_030_),
    .Y(_014_)
  );


  NAND2X1
  _100_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_output__6__.sout ),
    .Y(_031_)
  );


  OAI21X1
  _101_
  (
    .A(shift),
    .B(_045_),
    .C(_031_),
    .Y(_015_)
  );


  NAND2X1
  _102_
  (
    .A(test),
    .B(tck),
    .Y(_032_)
  );


  OAI21X1
  _103_
  (
    .A(test),
    .B(_048_),
    .C(_032_),
    .Y(\__uuf__.__clk_source__ )
  );


  NOR2X1
  _104_
  (
    .A(shift),
    .B(\__uuf__._10_ ),
    .Y(_033_)
  );


  AOI21X1
  _105_
  (
    .A(shift),
    .B(_047_),
    .C(_033_),
    .Y(_026_)
  );


  NOR2X1
  _106_
  (
    .A(shift),
    .B(\__uuf__._09_ ),
    .Y(_034_)
  );


  AOI21X1
  _107_
  (
    .A(shift),
    .B(_046_),
    .C(_034_),
    .Y(_025_)
  );


  NOR2X1
  _108_
  (
    .A(shift),
    .B(\__uuf__._08_ ),
    .Y(_035_)
  );


  AOI21X1
  _109_
  (
    .A(shift),
    .B(_044_),
    .C(_035_),
    .Y(_024_)
  );


  NAND2X1
  _110_
  (
    .A(shift),
    .B(\__uuf__.code_reg[6] ),
    .Y(_036_)
  );


  OAI21X1
  _111_
  (
    .A(shift),
    .B(_049_),
    .C(_036_),
    .Y(_023_)
  );


  NAND2X1
  _112_
  (
    .A(shift),
    .B(\__uuf__.code_reg[5] ),
    .Y(_037_)
  );


  OAI21X1
  _113_
  (
    .A(shift),
    .B(_050_),
    .C(_037_),
    .Y(_022_)
  );


  NAND2X1
  _114_
  (
    .A(shift),
    .B(\__uuf__.code_reg[4] ),
    .Y(_038_)
  );


  OAI21X1
  _115_
  (
    .A(shift),
    .B(_051_),
    .C(_038_),
    .Y(_021_)
  );


  NAND2X1
  _116_
  (
    .A(shift),
    .B(\__uuf__.code_reg[3] ),
    .Y(_039_)
  );


  OAI21X1
  _117_
  (
    .A(shift),
    .B(_052_),
    .C(_039_),
    .Y(_020_)
  );


  NAND2X1
  _118_
  (
    .A(shift),
    .B(\__uuf__.code_reg[2] ),
    .Y(_040_)
  );


  OAI21X1
  _119_
  (
    .A(shift),
    .B(_053_),
    .C(_040_),
    .Y(_019_)
  );


  NAND2X1
  _120_
  (
    .A(shift),
    .B(\__uuf__.code_reg[1] ),
    .Y(_041_)
  );


  OAI21X1
  _121_
  (
    .A(shift),
    .B(_054_),
    .C(_041_),
    .Y(_018_)
  );


  NAND2X1
  _122_
  (
    .A(shift),
    .B(\__uuf__.code_reg[0] ),
    .Y(_042_)
  );


  OAI21X1
  _123_
  (
    .A(shift),
    .B(_055_),
    .C(_042_),
    .Y(_017_)
  );


  NAND2X1
  _124_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_input__3__.sout ),
    .Y(_043_)
  );


  OAI21X1
  _125_
  (
    .A(shift),
    .B(_056_),
    .C(_043_),
    .Y(_016_)
  );


  INVX1
  _126_
  (
    .A(rst),
    .Y(_001_)
  );


  INVX1
  _127_
  (
    .A(rst),
    .Y(_002_)
  );


  INVX1
  _128_
  (
    .A(rst),
    .Y(_003_)
  );


  INVX1
  _129_
  (
    .A(rst),
    .Y(_004_)
  );


  INVX1
  _130_
  (
    .A(rst),
    .Y(_005_)
  );


  INVX1
  _131_
  (
    .A(rst),
    .Y(_006_)
  );


  INVX1
  _132_
  (
    .A(rst),
    .Y(_007_)
  );

  assign \__BoundaryScanRegister_input__0__.sout  = _133_;
  assign \_133_.d  = _008_;
  assign \__BoundaryScanRegister_input__1__.sout  = _134_;
  assign \_134_.d  = _009_;
  assign \__BoundaryScanRegister_input__2__.sout  = _135_;
  assign \_135_.d  = _010_;
  assign \__BoundaryScanRegister_input__3__.sout  = _136_;
  assign \_136_.d  = _011_;
  assign \__BoundaryScanRegister_output__4__.sout  = _137_;
  assign \_137_.d  = _012_;
  assign \__BoundaryScanRegister_output__5__.sout  = _138_;
  assign \_138_.d  = _013_;
  assign \__BoundaryScanRegister_output__6__.sout  = _139_;
  assign \_139_.d  = _014_;
  assign sout = _140_;
  assign \_140_.d  = _015_;

  INVX1
  \__uuf__._41_ 
  (
    .A(\__BoundaryScanRegister_input__3__.dout ),
    .Y(\__uuf__._11_ )
  );


  INVX1
  \__uuf__._42_ 
  (
    .A(\__BoundaryScanRegister_input__1__.dout ),
    .Y(\__uuf__._12_ )
  );


  INVX1
  \__uuf__._43_ 
  (
    .A(\__BoundaryScanRegister_input__0__.dout ),
    .Y(\__uuf__._13_ )
  );


  INVX1
  \__uuf__._44_ 
  (
    .A(\__BoundaryScanRegister_input__2__.dout ),
    .Y(\__uuf__._14_ )
  );


  NOR2X1
  \__uuf__._45_ 
  (
    .A(\__uuf__._13_ ),
    .B(rst),
    .Y(\__uuf__._00_ )
  );


  NOR2X1
  \__uuf__._46_ 
  (
    .A(\__uuf__._12_ ),
    .B(rst),
    .Y(\__uuf__._01_ )
  );


  NOR2X1
  \__uuf__._47_ 
  (
    .A(\__uuf__._14_ ),
    .B(rst),
    .Y(\__uuf__._02_ )
  );


  NOR2X1
  \__uuf__._48_ 
  (
    .A(\__uuf__._11_ ),
    .B(rst),
    .Y(\__uuf__._03_ )
  );


  XOR2X1
  \__uuf__._49_ 
  (
    .A(\__BoundaryScanRegister_input__1__.dout ),
    .B(\__BoundaryScanRegister_input__0__.dout ),
    .Y(\__uuf__._15_ )
  );


  XNOR2X1
  \__uuf__._50_ 
  (
    .A(\__BoundaryScanRegister_input__3__.dout ),
    .B(\__uuf__._15_ ),
    .Y(\__uuf__._16_ )
  );


  NOR2X1
  \__uuf__._51_ 
  (
    .A(rst),
    .B(\__uuf__._16_ ),
    .Y(\__uuf__._04_ )
  );


  XOR2X1
  \__uuf__._52_ 
  (
    .A(\__BoundaryScanRegister_input__0__.dout ),
    .B(\__BoundaryScanRegister_input__2__.dout ),
    .Y(\__uuf__._17_ )
  );


  XNOR2X1
  \__uuf__._53_ 
  (
    .A(\__BoundaryScanRegister_input__3__.dout ),
    .B(\__uuf__._17_ ),
    .Y(\__uuf__._18_ )
  );


  NOR2X1
  \__uuf__._54_ 
  (
    .A(rst),
    .B(\__uuf__._18_ ),
    .Y(\__uuf__._05_ )
  );


  XOR2X1
  \__uuf__._55_ 
  (
    .A(\__BoundaryScanRegister_input__1__.dout ),
    .B(\__BoundaryScanRegister_input__2__.dout ),
    .Y(\__uuf__._19_ )
  );


  XNOR2X1
  \__uuf__._56_ 
  (
    .A(\__BoundaryScanRegister_input__3__.dout ),
    .B(\__uuf__._19_ ),
    .Y(\__uuf__._20_ )
  );


  NOR2X1
  \__uuf__._57_ 
  (
    .A(rst),
    .B(\__uuf__._20_ ),
    .Y(\__uuf__._06_ )
  );


  XOR2X1
  \__uuf__._58_ 
  (
    .A(\__uuf__.code_reg[4] ),
    .B(\__uuf__.code_reg[0] ),
    .Y(\__uuf__._21_ )
  );


  XNOR2X1
  \__uuf__._59_ 
  (
    .A(\__uuf__.code_reg[1] ),
    .B(\__uuf__._21_ ),
    .Y(\__uuf__._22_ )
  );


  XNOR2X1
  \__uuf__._60_ 
  (
    .A(\__uuf__.code_reg[3] ),
    .B(\__uuf__._22_ ),
    .Y(\__uuf__._23_ )
  );


  XOR2X1
  \__uuf__._61_ 
  (
    .A(\__uuf__.code_reg[0] ),
    .B(\__uuf__.code_reg[5] ),
    .Y(\__uuf__._24_ )
  );


  XNOR2X1
  \__uuf__._62_ 
  (
    .A(\__uuf__.code_reg[2] ),
    .B(\__uuf__._24_ ),
    .Y(\__uuf__._25_ )
  );


  XNOR2X1
  \__uuf__._63_ 
  (
    .A(\__uuf__.code_reg[3] ),
    .B(\__uuf__._25_ ),
    .Y(\__uuf__._26_ )
  );


  XOR2X1
  \__uuf__._64_ 
  (
    .A(\__uuf__.code_reg[3] ),
    .B(\__uuf__._25_ ),
    .Y(\__uuf__._27_ )
  );


  NAND2X1
  \__uuf__._65_ 
  (
    .A(\__uuf__._23_ ),
    .B(\__uuf__._26_ ),
    .Y(\__uuf__._28_ )
  );


  XOR2X1
  \__uuf__._66_ 
  (
    .A(\__uuf__.code_reg[1] ),
    .B(\__uuf__.code_reg[6] ),
    .Y(\__uuf__._29_ )
  );


  XNOR2X1
  \__uuf__._67_ 
  (
    .A(\__uuf__.code_reg[2] ),
    .B(\__uuf__._29_ ),
    .Y(\__uuf__._30_ )
  );


  INVX1
  \__uuf__._68_ 
  (
    .A(\__uuf__._30_ ),
    .Y(\__uuf__._31_ )
  );


  XOR2X1
  \__uuf__._69_ 
  (
    .A(\__uuf__.code_reg[3] ),
    .B(\__uuf__._30_ ),
    .Y(\__uuf__._32_ )
  );


  XNOR2X1
  \__uuf__._70_ 
  (
    .A(\__uuf__.code_reg[3] ),
    .B(\__uuf__._30_ ),
    .Y(\__uuf__._33_ )
  );


  NAND3X1
  \__uuf__._71_ 
  (
    .A(\__uuf__._23_ ),
    .B(\__uuf__._26_ ),
    .C(\__uuf__._32_ ),
    .Y(\__uuf__._34_ )
  );


  XOR2X1
  \__uuf__._72_ 
  (
    .A(\__uuf__.code_reg[0] ),
    .B(\__uuf__._34_ ),
    .Y(\__uuf__._35_ )
  );


  NOR2X1
  \__uuf__._73_ 
  (
    .A(rst),
    .B(\__uuf__._35_ ),
    .Y(\__uuf__._07_ )
  );


  NAND3X1
  \__uuf__._74_ 
  (
    .A(\__uuf__._23_ ),
    .B(\__uuf__._27_ ),
    .C(\__uuf__._33_ ),
    .Y(\__uuf__._36_ )
  );


  XOR2X1
  \__uuf__._75_ 
  (
    .A(\__uuf__.code_reg[1] ),
    .B(\__uuf__._36_ ),
    .Y(\__uuf__._37_ )
  );


  NOR2X1
  \__uuf__._76_ 
  (
    .A(rst),
    .B(\__uuf__._37_ ),
    .Y(\__uuf__._08_ )
  );


  NOR3X1
  \__uuf__._77_ 
  (
    .A(\__uuf__._23_ ),
    .B(\__uuf__._27_ ),
    .C(\__uuf__._32_ ),
    .Y(\__uuf__._38_ )
  );


  XNOR2X1
  \__uuf__._78_ 
  (
    .A(\__uuf__.code_reg[2] ),
    .B(\__uuf__._38_ ),
    .Y(\__uuf__._39_ )
  );


  NOR2X1
  \__uuf__._79_ 
  (
    .A(rst),
    .B(\__uuf__._39_ ),
    .Y(\__uuf__._09_ )
  );


  MUX2X1
  \__uuf__._80_ 
  (
    .A(\__uuf__.code_reg[3] ),
    .B(\__uuf__._31_ ),
    .S(\__uuf__._28_ ),
    .Y(\__uuf__._40_ )
  );


  NOR2X1
  \__uuf__._81_ 
  (
    .A(rst),
    .B(\__uuf__._40_ ),
    .Y(\__uuf__._10_ )
  );

  assign \__uuf__.code_reg[0]  = \__uuf__._82_ ;
  assign \\__uuf__._82_.d  = _016_;
  assign \__uuf__.code_reg[1]  = \__uuf__._83_ ;
  assign \\__uuf__._83_.d  = _017_;
  assign \__uuf__.code_reg[2]  = \__uuf__._84_ ;
  assign \\__uuf__._84_.d  = _018_;
  assign \__uuf__.code_reg[3]  = \__uuf__._85_ ;
  assign \\__uuf__._85_.d  = _019_;
  assign \__uuf__.code_reg[4]  = \__uuf__._86_ ;
  assign \\__uuf__._86_.d  = _020_;
  assign \__uuf__.code_reg[5]  = \__uuf__._87_ ;
  assign \\__uuf__._87_.d  = _021_;
  assign \__uuf__.code_reg[6]  = \__uuf__._88_ ;
  assign \\__uuf__._88_.d  = _022_;
  assign \__BoundaryScanRegister_output__4__.din  = \__uuf__._89_ ;
  assign \\__uuf__._89_.d  = _023_;
  assign \__BoundaryScanRegister_output__5__.din  = \__uuf__._90_ ;
  assign \\__uuf__._90_.d  = _024_;
  assign \__BoundaryScanRegister_output__6__.din  = \__uuf__._91_ ;
  assign \\__uuf__._91_.d  = _025_;
  assign \__BoundaryScanRegister_output__4__.sin  = \__uuf__._92_ ;
  assign \\__uuf__._92_.d  = _026_;
  assign data_out = { \__BoundaryScanRegister_output__4__.sin , \__BoundaryScanRegister_output__6__.din , \__BoundaryScanRegister_output__5__.din , \__BoundaryScanRegister_output__4__.din  };

endmodule

